
server:
  port: 8090
  
spring:
  application:
    name: client1
  datasource:
    url: jdbc:mysql://localhost:3306/comprodb
    username: ea
    password: cs544
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
      
      
      
    
      


    