

server:
  port: 8088
  
spring:
  application:
    name: client1
  datasource:
    url: jdbc:mysql://localhost/comprodb
    username: ea
    password: cs544
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true